name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣  Grab your code
    - name: Checkout
      uses: actions/checkout@v4

    # 2️⃣  Set up JDK (same version Studio uses)
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3️⃣  Cache Gradle & wrapper
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    # 4️⃣  Make the debug APK (mobile module)
    - name: Assemble Debug
      run: ./gradlew :mobile:assembleDebug

    # 5️⃣  Upload artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Friday-Mobile-Debug
        path: mobile/build/outputs/apk/debug/mobile-debug.apk
